spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onepunch
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8087
mybatis-plus:
  mapper-locations:
    - mybatis-Nan.xml
